services:
  demo-start:
    build:
      dockerfile: Dockerfile.start
    ports:
      - 8080:80
    cap_add:
      - NET_ADMIN
    volumes:
      - .:/demo-files

  demo-final:
    build:
      dockerfile: Dockerfile.end